# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: core

on:
  push:
    paths:
      - '.github/workflows/build-and-deploy.yml'
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - '.parcelrc.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: cache install
        id: cache-install
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-install-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-install-
      - name: install
        #if: steps.cache-install.outputs.cache-hit != 'true'
        run: npm ci
      - name: cache build
        uses: actions/cache@v2
        with:
          path: .parcel-cache
          key: ${{ runner.os }}-build-${{ hashFiles('src/**') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: build
        run: npm run build:ghpages
      - name: upload app
        uses: actions/upload-artifact@master
        with:
          name: app
          path: dist
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
